### ISSUE TITLE
luigi.toml file generating error with 2.8.11, but works with 2.8.9

### ISSUE THREAD

**Issue by James-Hudson3010** [spotify/luigi#2898]
My luigi.toml file is just this...

```
[logging]
version = 1.0
disable_existing_loggers = false

[logging.handlers.console]
level = "DEBUG"
class = "logging.StreamHandler"
```

when using luigi 2.8.9, my task (```luigi --module tasks.test Test --local-scheduler```) runs just fine.

However, if I upgrade to 2.8.11, I get the following error:

```
Traceback (most recent call last):
  File "/Users/jamesh/.pyenv/versions/3.7.6/lib/python3.7/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/Users/jamesh/.pyenv/versions/3.7.6/lib/python3.7/logging/config.py", line 697, in configure_handler
    formatter = config.pop('formatter', None)
AttributeError: 'FrozenOrderedDict' object has no attribute 'pop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jamesh/depot/test/test_env/lib/python3.7/site-packages/luigi/retcodes.py", line 75, in run_with_retcodes
    worker = luigi.interface._run(argv).worker
  File "/Users/jamesh/depot/test/test_env/lib/python3.7/site-packages/luigi/interface.py", line 211, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/Users/jamesh/depot/test/test_env/lib/python3.7/site-packages/luigi/interface.py", line 145, in _schedule_and_run
    InterfaceLogging.setup(env_params)
  File "/Users/jamesh/depot/test/test_env/lib/python3.7/site-packages/luigi/setup_logging.py", line 83, in setup
    configured = cls._section(opts)
  File "/Users/jamesh/depot/test/test_env/lib/python3.7/site-packages/luigi/setup_logging.py", line 48, in _section
    logging.config.dictConfig(logging_config)
  File "/Users/jamesh/.pyenv/versions/3.7.6/lib/python3.7/logging/config.py", line 800, in dictConfig
    dictConfigClass(config).configure()
  File "/Users/jamesh/.pyenv/versions/3.7.6/lib/python3.7/logging/config.py", line 571, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'console'
```

**Comment by James-Hudson3010** [comment]
I checked and it works with 2.8.10 as well. The bug appears in 2.8.11.

**Comment by hirolau** [comment]
This is very much related to issue [2879](https://github.com/spotify/luigi/issues/2879). The standard library logging module expects a mutable dict, but the config for TOML was changed to use in internal FrozenOrderedDict

There are two ways to slove it. Ignore the freezing of the logging section in TOML configs, or create an unfreeze method and call it before passing the dict to the logging config.
