### ISSUE TITLE
New boto3 client usage in 2.7.6 throws error

### ISSUE THREAD

**Issue by robin-weiss-sm** [spotify/luigi#2484]
After updating Luigi to 2.7.6 my tasks that use the luigi.contrib.s3 module crash with a failing call to boto3. Looking at the release notes I found that the release included the switch from the old botocore to boto3 client. 

I updated boto3 and botocore to latest version but still got the following error

```python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/luigi/contrib/s3.py", line 157, in s3
    **options)
  File "/opt/conda/lib/python3.6/site-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
TypeError: resource() got an unexpected keyword argument 'host'
```

Apparently boto3 removed the deprecated "host" parameter in some of the newer releases and hence the error. Is there a missing dependency link for the specific boto3 version or is my environment just misconfigured? 

For now downgrading to Luigi 2.7.5 solved my problems.

Thanks :)

**Comment by dlstadther** [comment]
Thanks for reporting @robin-weiss-sm 

I'm not familiar with boto2's `host` kwarg. Is this a boto3 improvement you'd like to PR? It would be a much appreciated patch :)

**Comment by HyunTruth** [comment]
I had the same problem, and I think its not an environment error but rather the code error. 
Removing the host kwarg from
`s3.S3Client()`
made the codes work for me.

**Comment by dlstadther** [comment]
@HyunTruth Boto3 is expected to have some conflicts with Boto(2) kwargs.

While I did not use the boto kwarg `host`, I know there must be a boto3 alternative. For now, we may need to include `host` in the [deprecated args checker](https://github.com/spotify/luigi/blob/master/luigi/contrib/s3.py#L518-L526)

**Comment by HyunTruth** [comment]
@dlstadther Okay, I'll try to look through the boto3 alternative of kwargs. If not found, then I'll at least try to PR this issue for deprecated_args_checker

**Comment by HyunTruth** [comment]
@dlstadther The most recent version of botocore seems to use `region_name` for kwarg instead of `host`. I'll elaborate further on it

**Comment by dlstadther** [comment]
Thanks for investigating, @HyunTruth ! Feel free to PR anything you may find helpful in resolving this and providing guidance to others who encounter this issue :)

**Comment by HyunTruth** [comment]
@dlstadther added `s3client check for deprecated host keyword and raise error with the details` #2493 PR to address this issue

**Comment by dlstadther** [comment]
Resolved by #2493
