### PR TITLE
fix(server): resolve /history 500 error by correcting importlib.resources usage

### LINKED ISSUE #3415: Scheduler /history endpoint throws 500 Server Error
### Problem

The /history endpoint in the scheduler web UI fails with a 500 error.

### Steps to reproduce

Using Python 3.13:

```
> pip install 'luigi==3.8.0' 'sqlalchemy<1.4'
...

> cat << EOF > luigi.cfg
[scheduler]
record_task_history = True

[task_history]
db_connection = sqlite:///history.sqlite
EOF

> luigid
...
```

Then visit http://localhost:8082/history

### Expected behaviour

Task history UI is shown.

### Actual behaviour

"500: Internal Server Error" is shown.

Logs from luigid:
```
2026-04-08 15:22:19,391 tornado.application[87851] ERROR: Uncaught exception GET /history (::1)
HTTPServerRequest(protocol='http', host='localhost:8082', method='GET', uri='/history', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/arthurb/.virtualenvs/temp/lib/python3.13/site-packages/tornado/web.py", line 1878, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/arthurb/.virtualenvs/temp/lib/python3.13/site-packages/luigi/server.py", line 236, in get
    self.render("recent.html", tasks=tasks)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/arthurb/.virtualenvs/temp/lib/python3.13/site-packages/tornado/web.py", line 1025, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/arthurb/.virtualenvs/temp/lib/python3.13/site-packages/tornado/web.py", line 1157, in render_string
    template_path = self.get_template_path()
  File "/Users/arthurb/.virtualenvs/temp/lib/python3.13/site-packages/luigi/server.py", line 160, in get_template_path
    return importlib.resources.files("templates").name
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'resources'
2026-04-08 15:22:19,397 tornado.access[87851] ERROR: 500 GET /history (::1) 13.44ms
```

### Notes

It looks like the relevant change was fc62c364c76ed2ba3fc08e263712b6d9489dbde7, so this affects 3.7.3+. Should be an easy fix.

### PR DESCRIPTION
**Pull request by dlstadther**
## Description

Replaces the broken `importlib.resources` usage in `BaseTaskHistoryHandler.get_template_path()` with the simpler `os.path` approach already used for `static_path` in the same file.

The previous code had three problems introduced in fc62c364 when `pkg_resources` was removed:
1. `import importlib` does not make `importlib.resources` available — it must be explicitly imported as a submodule
2. `files("templates")` references a non-existent top-level package named `"templates"`; the correct anchor is `"luigi"`
3. `.name` returns only the basename ("templates"), not the full filesystem path that Tornado requires

The fix uses `os.path.join(os.path.dirname(__file__), "templates")`, which is already the established pattern for `static_path` on the line immediately below and requires no new imports.

## Motivation and Context

Fixes #3415 . Visiting `/history` on any luigi scheduler with `record_task_history = True` results in a 500 Internal Server Error on luigi 3.7.3+ due to the AttributeError described above. This affects all supported Python versions (3.10–3.13).

## Have you tested this? If so, how?
 

New test included.

I also manually reproduced the 500 error against a fresh Python 3.13 environment with luigi==3.8.0 and confirmed the fix resolves it (using the "Steps to reproduce" included in the linked Issue).

### CODE REVIEW

**Comment by dlstadther** [comment]
@RRap0so , could you review? Feel free to tag some other folk who i should be raises requests to.

**Comment by dlstadther** [comment]
@cjordn , i've seen you help with updating some CI settings recently. Would you be comfortable helping with a couple reviews? This one and the linked release.

If not, would you be able to direct me towards some other folks who could help out? (While this project doesn't get the attention it once did, we have a maintainer bottleneck)

**Review by RRap0so — APPROVED** [review]
