### ISSUE TITLE
Error when prunning workers from old scheduler states

### ISSUE THREAD

**Issue by tgalery** [spotify/luigi#1991]
Hi there, we have been using luigi at work where we developed an extension for managing some data pipelines. This extension used luigi 1.3 and I've been working on a upgrade to 2.5. I think I found a bug when the scheduler loads tasks from previous pickled states. When I submit tasks via `luigi.interface.build`, I get the following error on the `luigid` side:

```
2017-01-18 14:47:18,248 tornado.application[56530] ERROR: Uncaught exception GET /api/add_task (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8082', method='GET', uri='/api/add_task', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Encoding': 'gzip, deflate', 'Content-Length': '789', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'localhost:8082', 'Accept': '*/*', 'Connection': 'keep-alive', 'User-Agent': 'python-requests/2.4.1 CPython/3.4.5 Darwin/15.6.0'})
Traceback (most recent call last):
  File "/Users/thiago/miniconda2/envs/rendang/lib/python3.4/site-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/thiago/miniconda2/envs/rendang/lib/python3.4/site-packages/luigi/server.py", line 77, in get
    result = getattr(self._scheduler, method)(**arguments)
  File "/Users/thiago/miniconda2/envs/rendang/lib/python3.4/site-packages/luigi/scheduler.py", line 781, in add_task
    if task.batch_id is not None:
AttributeError: 'Task' object has no attribute 'batch_id'
```

This then triggers a worker prune:

```
2017-01-18 14:47:18,248 tornado.access[56530] ERROR: 500 GET /api/add_task (127.0.0.1) 1.18ms
2017-01-18 14:47:38,831 luigi.scheduler[56530] INFO: Starting pruning of task graph
2017-01-18 14:47:38,831 tornado.application[56530] ERROR: Exception in callback <bound method Scheduler.prune of <luigi.scheduler.Scheduler object at 0x1044e0128>>
Traceback (most recent call last):
  File "/Users/thiago/miniconda2/envs/rendang/lib/python3.4/site-packages/tornado/ioloop.py", line 1041, in _run
    return self.callback()
  File "/Users/thiago/miniconda2/envs/rendang/lib/python3.4/site-packages/luigi/scheduler.py", line 680, in prune
    self._prune_workers()
  File "/Users/thiago/miniconda2/envs/rendang/lib/python3.4/site-packages/luigi/scheduler.py", line 692, in _prune_workers
    self._state.inactivate_workers(remove_workers)
  File "/Users/thiago/miniconda2/envs/rendang/lib/python3.4/site-packages/luigi/scheduler.py", line 624, in inactivate_workers
    self._remove_workers_from_tasks(delete_workers)
  File "/Users/thiago/miniconda2/envs/rendang/lib/python3.4/site-packages/luigi/scheduler.py", line 630, in _remove_workers_from_tasks
    task.workers -= workers
TypeError: unsupported operand type(s) for -=: 'set' and 'list'
```
Deleting `state.pickle` from my current file system allowed me to run things smoothly again, but this might point to a codepath that is not used very often and maybe some extra defenses need to be put in place.

**Comment by Tarrasch** [comment]
It's not a bug. We usually put in backward compatibilities but we don't maintain them for ever and ever.

---

That said, I've for long wanted to just remove the state-file as I find it to cause 95% harm 5% good. What do you think @tgalery, when you did the migration, was it important that state was preserved? In all (2) setups I've worked with, the clients will always rebuild the dependency graphs anyway.

**Comment by tgalery** [comment]
For us, it's not important at all, since we run tasks by deploying a luigi server for a specific purpose and then tearing it down. Should I close the issue, or leave it open so people can manifest their opinion on the matter ?

**Comment by Tarrasch** [comment]
I think I close it. I've however thought of raising to the mailing group but I got lazy and didnt. :)
